### ISSUE TITLE
Upgrade to maragu.dev/gomponents namespace

### ISSUE THREAD

**Issue by markuswustenberg** [PiotrKowalski/html-to-gomponents#10]
Hey @PiotrKowalski,

I'm in the process of moving gomponents to the maragu.dev/gomponents namespace. Could you update your online converter tool to use that one instead of github.com/maragudk/gomponents? 😊

**Comment by PiotrKowalski** [comment]
@markuswustenberg 
It should be updated now. Sorry that it took so long. I just couldn't find time to do it. Factorio and Sati :-;
Btw,
I saw you doing something similar officially. 
Should I stop this project then?

**Comment by markuswustenberg** [comment]
Thank you! You’re doing this for free for the community, take as long as you like. 😊

No, I definitely think this still has value! I use it myself. :D But yeah, I’m looking into building a CLI.
