### ISSUE TITLE
Proposal: make converter code into a library

### ISSUE THREAD

**Issue by cachesdev** [PiotrKowalski/html-to-gomponents#6]
currently everything in inside internal, which means that if I wanted to use this code as a library I would need to clone and modify it. this is a problem as it would be impossible to update from upstream without considerable manual work. I propose moving eveything inside internal to a `pkg` or even the root.

**Comment by PiotrKowalski** [comment]
Could you describe it in more detail?
I am not sure why you would need to use this tool inside a code.
If you really want to have it, I could expose some functions for you outside of `/internal`

**Comment by cachesdev** [comment]
Mainly that the website has a size limit, I couldn't convert a really huge component (the daisyui site theme picker, if you are curious). It would also make it possible to automate when one may have many files that they want to convert quickly

**Comment by PiotrKowalski** [comment]
Hi
Can you check #9 and if it works for you?
It gives you whole response such as on the website.

If you want, I can add also some raw output, so without the whole golang file structure

**Comment by cachesdev** [comment]
@PiotrKowalski I am really sorry for the late response, had a busy weekend. yes, this is exactly what I needed! thanks
